// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Auto-generate the sidebar from the `docs/` file tree. Add more pages
  // and they'll appear here automatically.
  docs: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
